PLAYER_SPRITE_PATH = 'sprites/circle-white.png'
PLAYER_SPRITE_SIZE = 80
PLAYER_SPEED_LIMIT = 5
PLAYER_ACCEL = 0.5
PLAYER_FRICT = 0.9
BULLET_SPRITE_PATH = 'sprites/circle-white.png'
BULLET_SPRITE_SIZE = 16
BULLET_SPEED = 6.0
BULLET_COOLDOWN = 10
BULLET_MOMENTUM = 0.1   # shooter_vel * BULLET_MOMENTUM = bullet_vel (kinda)
BULLET_DESPAWN_RANGE = 50
TRACING_ENABLED = false